-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgRuSE1CKBvtY/jmsl
RBTS4kXxpOyxL1Pf1yD/yINXKfqgCgYIKoZIzj0DAQehRANCAAQ8nqfYblEePU9s
5Wch9kCh9i0esGWA79YRzwxS0nHjG5sMYp4Y1ZLfCv1NeikeP8biV2e8BCdmBdcC
BNgs+QFV
-----END PRIVATE KEY-----